# DAWN Tick Engine Configuration

# Timing settings
tick_engine:
  tick_interval: 0.1
  tick_interval_min: 0.05
  tick_interval_max: 1.0
  max_ticks: null
  max_errors: 5
  error_retry_delay: 2.0
  cooldown_ticks: 10
  heat_threshold: 0.8
  cairn_enabled: true

# Error handling
max_errors: 5              # Maximum consecutive errors before shutdown
error_retry_delay: 2.0     # Delay before retrying after error

# Subsystems to load
subsystems:
  - name: pulse
    enabled: true
    priority: 1
  - name: schema_evolution_engine
    enabled: true
    priority: 2
  - name: thermal_visualizer
    enabled: true
    priority: 3
  - name: entropy_visualizer
    enabled: true
    priority: 4
  - name: alignment_visualizer
    enabled: true
    priority: 5
  - name: bloom_visualizer
    enabled: true
    priority: 6
  - name: dawn_visualizer
    enabled: true
    priority: 7

# System thresholds
thresholds:
  scup_trigger: 0.8        # SCUP threshold for Claude query
  heat_critical: 0.95      # Critical heat level for shutdown
  entropy_high: 0.7        # High entropy warning level

# Claude integration (cairn)
cairn:
  enabled: true
  cooldown: 30.0           # Seconds between Claude queries
  max_queries_per_hour: 10

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/tick_log.jsonl"
  max_size: 10485760  # 10MB
  backup_count: 5

# Performance monitoring
performance:
  monitor_interval: 5.0    # System monitoring interval
  metrics_buffer_size: 100 # Number of metrics to keep in memory
  metrics_enabled: true
  profile_ticks: false
  memory_tracking: true