@echo off
echo 🌅 WAKING DAWN...

echo 🧠 Starting Tick Engine...
start /B python main_with_weight_charge.py

echo 🦉 Binding Owl Tracer...
start /B python codex\owl_bound_boot.py

echo 🌈 Loading mood → heat logic...
start /B python semantic\mood_map_loader.py

echo 🌸 Generating fractal bloom signatures...
start /B python fractal_generator.py

echo 🕸️ Animating mycelium root density...
start /B python mycelium_animation.py

echo 🌪️ Rendering drift-entropy hybrid field...
start /B python semantic\animate_drift_entropy.py

echo 🧬 Visualizing rebloom trail maps...
start /B python semantic\rebloom_trail_animation.py

echo ⚡ Activating trigger rule engine...
start /B python semantic_trigger_rules.py

echo 📊 Printing pulse report to console...
python debug\console_report.py

echo ✅ DAWN is awake and running.
pause
