log_level: INFO
tick_rate: 5.0
tick_interval: 0.2
tick_interval_min: 0.1
tick_interval_max: 5.0
max_errors: 3
subsystems:
  pulse:
    priority: 1
  schema:
    priority: 2
  visual:
    priority: 3
  thermal:
    priority: 4
  entropy:
    priority: 5
  alignment:
    priority: 6
  bloom:
    priority: 7
